version: '3'
services:
  prod-container:
    image: lammerfalcon/nuxt3:latest
    ports:
      - "4000:3000"
    restart: always

  dev-container:
    image: lammerfalcon/nuxt3:latest
    ports:
      - "5000:3001"
    restart: always
