version: '3'
services:
  prod-container:
    image: lammerfalcon/nuxt3:latest
    ports:
      - "3000:3000"
    restart: always

  dev-container:
    image: lammerfalcon/nuxt3:dev
    ports:
      - "3001:3001"
    restart: always
