name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set environment variables
        run: |
          export TAG=latest
          export PORT=3000

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for main
        run: |
          docker build -t lammerfalcon/nuxt3:latest .
          docker push lammerfalcon/nuxt3:latest

      - name: Deploy to VPS (Main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull lammerfalcon/nuxt3:latest
            cd service/main/vps
            git pull
            docker-compose up -d --build

  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set environment variables
        run: |
          export TAG=dev
          export PORT=3001

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for dev
        run: |
          docker build -t lammerfalcon/nuxt3:dev .
          docker push lammerfalcon/nuxt3:dev

      - name: Deploy to VPS (Dev)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull lammerfalcon/nuxt3:dev
            cd service/dev/vps
            git pull
            docker-compose up -d --build
