name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TAG="latest"
          else
            TAG="dev"
          fi
          docker build -t lammerfalcon/nuxt3:$TAG .
          docker push lammerfalcon/nuxt3:$TAG

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              TAG="latest"
              PORT="3000"
              SUBDOMAIN="mysite.com"
              DEPLOY_DIR="service/main/vps"
              BRANCH="main"
            else
              TAG="dev"
              PORT="3001"
              SUBDOMAIN="dev.mysite.com"
              DEPLOY_DIR="service/dev/vps"
              BRANCH="dev"
            fi
            docker pull lammerfalcon/nuxt3:$TAG
            export TAG=$TAG
            export PORT=$PORT
            export SUBDOMAIN=$SUBDOMAIN
            export DEPLOY_DIR=$DEPLOY_DIR
            export BRANCH=$BRANCH
            cd $DEPLOY_DIR
            git pull
            git checkout $BRANCH
            docker-compose up -d --build
